#!/usr/bin/env zsh

# If the client folder already exist, assume that it's a re-install
# and that all the following isn't needed
[ -e client ] && exit 0

git clone https://github.com/inventaire/inventaire-client.git ./client

mkdir -p logs/archives/server logs/archives/errors deploy run db/leveldb
npm run patches

echo 'trying to clone git clone -b i18n https://github.com/inventaire/inventaire.git ./server/lib/emails/i18n/src'
git clone -b i18n https://github.com/inventaire/inventaire.git ./server/lib/emails/i18n/src
mkdir -p ./server/lib/emails/i18n/dist
./server/lib/emails/i18n/src/generate_lang_json.coffee all

# Expected by scripts/archive_logs
mkdir -p ./logs
touch ./logs/server.log ./logs/error.log
# Expected by scripts/actions/backup_databases.coffee
mkdir -p ./db/couchdb/backups
# Expected by scripts/test_api
mkdir -p run
touch run/3006 run/3009

# Init CouchDB and ElasticSearch databases synchronize
npm run elasticsync:init

# Create a local config file
emptyConfigFile="
# Override settings from ./default.coffee in this file
module.exports =
  db:
    username: 'yourcouchdbusername'
    password: 'yourcouchdbpassword'
"
echo "$emptyConfigFile" >> ./config/local.coffee

npm run install-client
